In [1]:
import numpy as np 

In [7]:
a = np.array([10, 15, 20, 25, 30, 2, 11, 10, 18, 16, 8, 19, 6, 110]) # une fois que vous avez créer ce tableau on ne peut plus rien ajouter en plus 

In [11]:
# valeur > 10 

mask = a > 10

In [13]:
numbersSup10 = a[mask]

In [14]:
sum(numbersSup10)

np.int64(264)

In [15]:
mask

array([False,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True, False,  True])

In [16]:
sum(mask)

np.int64(9)

In [18]:
# je voudrai les valeurs supérieur à 15 et inférieur 30

# valeur > 15 ET valeur < 30

mask = (a > 15) & (a < 30) # la syntaxe veut que si vous avez deux test logique ou comparaison il faut qu'ils soient entre parenthèses

In [19]:
sum(mask)

np.int64(5)

In [20]:
a[mask]

array([20, 25, 18, 16, 19])

In [21]:
t = np.array([True, True, True, False ])
sum(t)

np.int64(3)

In [22]:
# Trouvez le nombre de valeurs qui sont supérieur à 100 et affichez les
# Trouvez le nombre de valeur supérieur ou égale à 10

In [23]:
mask = a > 100 
print(sum(mask))

1


In [24]:
a[mask]

array([110])

In [26]:
mask = a >=10
sum(mask)

np.int64(11)

In [27]:
a[mask]

array([ 10,  15,  20,  25,  30,  11,  10,  18,  16,  19, 110])

In [28]:
matrix = np.array([[1, 2], [3, 4]]) # 2D 2x2
matrix

array([[1, 2],
       [3, 4]])

In [29]:
# Affichez sur la première ligne la deuxième valeur

In [37]:
matrix[0][1], matrix[0,1]

(np.int64(2), np.int64(2))

In [34]:
# qu'est ce que ça fait cette ligne 
matrix[0,:]

array([1, 2])

In [38]:
# affichez tous les éléments de la première colonne

In [40]:
matrix[:, 0] # je sélectionne toutes les lignes et je prends la première colonne

array([1, 3])

In [42]:
matrix[:, :] # toutes les lignes et toutes les colonnes

array([[1, 2],
       [3, 4]])

In [43]:
matrix[0]

array([1, 2])

In [47]:
# LIGNE COLONNE

array([], dtype=int64)

In [50]:
A = np.random.randint(0, 100, size=(3, 4) )
A

array([[14, 47,  2, 78],
       [83,  8, 91, 13],
       [44, 33, 82, 68]])

In [51]:
# Affichez la première ligne puis la deuxième
A[0,:] # A[0]

array([14, 47,  2, 78])

In [52]:
A[1,:]

array([83,  8, 91, 13])

In [53]:
# deuxième colonne 
A[:, 1]

array([47,  8, 33])

In [54]:
# Avec slicing affichez les deux derrnière valeurs de la ligne 
A[0,2:]

array([ 2, 78])

In [56]:
collect = np.zeros((2,3))

In [57]:
collect[0, 0] = 1

In [58]:
collect

array([[1., 0., 0.],
       [0., 0., 0.]])

In [59]:
B = np.array([1, 2, 3])

In [60]:
B**2

array([1, 4, 9])

In [63]:
B = 2*B + B**2 + 2 # equation du second degré vectorisé 

In [65]:
B*0.8 # baisse de 20% de chacune de nos valeurs

array([ 4. ,  8. , 13.6])

In [66]:
B.mean()

np.float64(10.666666666666666)

In [67]:
np.sum

<function sum at 0x1078f6fb0>