In [1]:
import numpy as np

In [17]:
january = np.array([-2,  5, -5,  6, -2,  0,  6,  2,  8,  0,  6, -1,  3,  3,  7,  0, -5,
        7,  4,  7,  8, -1,  5, -2,  3, -3, -2,  7,  8,  4,  2], dtype='float64')


In [18]:
# 1. Donnez toutes les températures qui sont supérieures à 0.
mask_temp_postive = january > 0
# mask
january[mask_temp_postive]

array([5., 6., 6., 2., 8., 6., 3., 3., 7., 7., 4., 7., 8., 5., 3., 7., 8.,
       4., 2.])

In [7]:
# 2. Comparez les températures supérieures et inférieures à 0."

# y a t il plus de valeurs positives que de valeurs négatives 
np.sum(january > 0) > np.sum(january <= 0)

np.True_

In [11]:
# 3. Donnez le pourcentage des températures positives sur le mois.

round( ( np.sum(january > 0) / len(january))*100, 1 )

np.float64(61.3)

### 4. Créez un tableau days pour les jours du mois et donnez les jours pour lesquels la température était supérieure à 0."

In [14]:
days = np.arange( 1, len(january) + 1  )
days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [19]:
# Les jours pour lesquels la température étaient positives
days[ mask_temp_postive ]

array([ 2,  4,  7,  8,  9, 11, 13, 14, 15, 18, 19, 20, 21, 23, 25, 28, 29,
       30, 31])

In [ ]:
# 5. Donnez toutes les températures supérieures à 0 à partir du dixième jour du mois.

In [23]:
# print( (days >= 10 ) )
print( (days >= 10 ) & mask_temp_postive )
mask_temp_days = (days >= 10 ) & mask_temp_postive 

[False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]
[False False False False False False False False False False  True False
  True  True  True False False  True  True  True  True False  True False
  True False False  True  True  True  True]


In [25]:
print( january[mask_temp_days] )
print( days[mask_temp_days] )

[6. 3. 3. 7. 7. 4. 7. 8. 5. 3. 7. 8. 4. 2.]
[11 13 14 15 18 19 20 21 23 25 28 29 30 31]


In [26]:
# une autre manière de faire 
january[9:][ january[9:] > 0 ]

array([6., 3., 3., 7., 7., 4., 7., 8., 5., 3., 7., 8., 4., 2.])

In [29]:
# permet de rassembler les valeurs 
# list( zip( january[mask_temp_days],  days[mask_temp_days] ) )

In [30]:
med = np.median( january ) 

In [31]:
january[ january < 0 ] = med # assigné la médiane au valeurs négative 

In [32]:
january

array([3., 5., 3., 6., 3., 0., 6., 2., 8., 0., 6., 3., 3., 3., 7., 0., 3.,
       7., 4., 7., 8., 3., 5., 3., 3., 3., 3., 7., 8., 4., 2.])